// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXatk7S2lPyqpytwifvXQNw-xBiRYKJJ4',
    appId: '1:774464135463:web:0fe71a296368d3c8d78902',
    messagingSenderId: '774464135463',
    projectId: 'worth-all',
    authDomain: 'worth-all.firebaseapp.com',
    storageBucket: 'worth-all.appspot.com',
    measurementId: 'G-3H1SYH66X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3O65-IkjMjj7WxLTRtEwwmSJ_BJg-LcU',
    appId: '1:774464135463:android:8b85d1fcff81b203d78902',
    messagingSenderId: '774464135463',
    projectId: 'worth-all',
    storageBucket: 'worth-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz9mrdxILcloKezPFxkzWLgLkRNOCgnvQ',
    appId: '1:774464135463:ios:c24c05383ced8b08d78902',
    messagingSenderId: '774464135463',
    projectId: 'worth-all',
    storageBucket: 'worth-all.appspot.com',
    androidClientId: '774464135463-536ko74gtu43akqi9ciqhkqud5chrb4u.apps.googleusercontent.com',
    iosClientId: '774464135463-30kqbua88mpd39mq2tt5oc4eva1j5l6l.apps.googleusercontent.com',
    iosBundleId: 'com.allstudio.worth',
  );
}
